/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import javax.swing.ImageIcon;

/**
 *
 * @author Manuel
 */
public class MenuUI extends javax.swing.JFrame {
    
    //Creamos los objetos que nos harán falta para añadirle funcionalidad a la interfaz
    PersonalUI personal = new PersonalUI();
    ArmamentoUI armamento = new ArmamentoUI();
    VehiculosUI vehiculos = new VehiculosUI();
    TransmisionesUI transmisiones = new TransmisionesUI();
    ConsultaUI consultas = new ConsultaUI();
    LoginUI login = new LoginUI();
    
    public MenuUI() {
        initComponents();
        //setIconImage(new ImageIcon(getClass().getResource("/resources/insignia.png")).getImage());
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        botonPersonal = new javax.swing.JButton();
        botonArmamento = new javax.swing.JButton();
        botonVehiculos = new javax.swing.JButton();
        BotonTransmisiones = new javax.swing.JButton();
        botonConsultas = new javax.swing.JButton();
        botonCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        //jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Insignia militar.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel1)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 420));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        botonPersonal.setFont(new java.awt.Font("Verdana Pro Cond", 0, 12)); // NOI18N
        botonPersonal.setText("Personal");
        botonPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPersonalActionPerformed(evt);
            }
        });

        botonArmamento.setFont(new java.awt.Font("Verdana Pro Cond", 0, 12)); // NOI18N
        botonArmamento.setText("Armamento");
        botonArmamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonArmamentoActionPerformed(evt);
            }
        });

        botonVehiculos.setFont(new java.awt.Font("Verdana Pro Cond", 0, 12)); // NOI18N
        botonVehiculos.setText("Vehículos");
        botonVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVehiculosActionPerformed(evt);
            }
        });

        BotonTransmisiones.setFont(new java.awt.Font("Verdana Pro Cond", 0, 12)); // NOI18N
        BotonTransmisiones.setText("Transmisiones");
        BotonTransmisiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTransmisionesActionPerformed(evt);
            }
        });

        botonConsultas.setFont(new java.awt.Font("Verdana Pro Cond", 0, 12)); // NOI18N
        botonConsultas.setText("Consultas");
        botonConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultasActionPerformed(evt);
            }
        });

        botonCerrarSesion.setFont(new java.awt.Font("Verdana Pro Cond", 0, 12)); // NOI18N
        botonCerrarSesion.setText("Cerrar sesion");
        botonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(botonConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonTransmisiones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonVehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonArmamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(botonPersonal)
                .addGap(18, 18, 18)
                .addComponent(botonArmamento)
                .addGap(18, 18, 18)
                .addComponent(botonVehiculos)
                .addGap(18, 18, 18)
                .addComponent(BotonTransmisiones)
                .addGap(18, 18, 18)
                .addComponent(botonConsultas)
                .addGap(18, 18, 18)
                .addComponent(botonCerrarSesion)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 320, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPersonalActionPerformed
        // Boton que nos lleva a personal
        personal.setVisible(true);
        dispose();   
    }//GEN-LAST:event_botonPersonalActionPerformed

    private void botonArmamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonArmamentoActionPerformed
        // Boton que nos lleva a armamento
        armamento.setVisible(true);
        dispose(); 
        
    }//GEN-LAST:event_botonArmamentoActionPerformed

    private void botonVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVehiculosActionPerformed
        // Boton que nos lleva a vehiculos
        vehiculos.setVisible(true);
        dispose(); 
        
    }//GEN-LAST:event_botonVehiculosActionPerformed

    private void BotonTransmisionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTransmisionesActionPerformed
        // Boton que nos lleva a transmisiones
        
        transmisiones.setVisible(true);
        dispose(); 
        
    }//GEN-LAST:event_BotonTransmisionesActionPerformed

    private void botonConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultasActionPerformed
        //Boton que nos lleva a consultas
        consultas.setVisible(true);
        dispose(); 
        
    }//GEN-LAST:event_botonConsultasActionPerformed

    private void botonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarSesionActionPerformed
        // Boton de cierre de sesion que nos lleva a login 
        login.setVisible(true);
        dispose(); 
        
    }//GEN-LAST:event_botonCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonTransmisiones;
    private javax.swing.JButton botonArmamento;
    private javax.swing.JButton botonCerrarSesion;
    private javax.swing.JButton botonConsultas;
    private javax.swing.JButton botonPersonal;
    private javax.swing.JButton botonVehiculos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
