/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import clases.Transmisiones;
import clases.TransmisionesClass;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Manuel
 */
public class TransmisionesUI extends javax.swing.JFrame {

    //Creamos los objetos que nos harán falta 
    TransmisionesClass transmisionesClass = new TransmisionesClass();
    Transmisiones transmisiones = new Transmisiones();
    DefaultTableModel tablaModelo;
    VehiculosUI vehiculosUI;
    ArmamentoUI armamentoUI;
    PersonalUI personalUI;
    ConsultaUI consultasUI;
    MenuUI menuUI;
            
    
    public TransmisionesUI() {
        initComponents();
        //setIconImage(new ImageIcon(getClass().getResource("/resources/insignia.png")).getImage());
        this.setLocationRelativeTo(null);
    }
    
    public void listaTransmisiones(){
        
        /*Creamos una lista en la cual almacenaremos los datos de nuestra base de datos
        y la añadimos a la tabla de nuestra interfaz para que esten visibles*/
        List <TransmisionesClass> listaTransmisiones = transmisiones.listaTransmisiones();
        tablaModelo = (DefaultTableModel) tablaTransmisiones.getModel();
        Object[] object = new Object[5];
        
        tablaModelo.setRowCount(0);
        
        //Recorremos con un bucle for y añadimos a la tabla
        for (int i = 0; i < listaTransmisiones.size(); i++) {
            
            object[0] = listaTransmisiones.get(i).getNumeroTransmision();
            object[1] = listaTransmisiones.get(i).getNombreTransmision();
            object[2] = listaTransmisiones.get(i).getTipo();
            object[3] = listaTransmisiones.get(i).getEstado();
            object[4] = listaTransmisiones.get(i).getTIM();
            
            tablaModelo.addRow(object);
            
        }
        
        tablaTransmisiones.setModel(tablaModelo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textNumTra = new javax.swing.JTextField();
        textNomTra = new javax.swing.JTextField();
        textTipTra = new javax.swing.JTextField();
        textEstTra = new javax.swing.JTextField();
        textTimTra = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTransmisiones = new javax.swing.JTable();
        insertTransmisiones = new javax.swing.JButton();
        modificarTransmisiones = new javax.swing.JButton();
        BotonRegistros = new javax.swing.JButton();
        eliminarTransmision = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        botonConsultas = new javax.swing.JButton();
        botonMenu = new javax.swing.JButton();
        botonArmamento = new javax.swing.JButton();
        botonVehiculos = new javax.swing.JButton();
        botonPersonal = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Verdana Pro Cond", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Número");

        jLabel2.setFont(new java.awt.Font("Verdana Pro Cond", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Verdana Pro Cond", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo");

        jLabel4.setFont(new java.awt.Font("Verdana Pro Cond", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Estado");

        jLabel5.setFont(new java.awt.Font("Verdana Pro Cond", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TIM");

        tablaTransmisiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Nombre", "Tipo", "Estado", "TIM"
            }
        ));
        tablaTransmisiones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaTransmisionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaTransmisiones);

        insertTransmisiones.setFont(new java.awt.Font("Verdana Pro Cond", 0, 12)); // NOI18N
        insertTransmisiones.setText("Insertar");
        insertTransmisiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertTransmisionesActionPerformed(evt);
            }
        });

        modificarTransmisiones.setFont(new java.awt.Font("Verdana Pro Cond", 0, 12)); // NOI18N
        modificarTransmisiones.setText("Modificar");
        modificarTransmisiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarTransmisionesActionPerformed(evt);
            }
        });

        BotonRegistros.setFont(new java.awt.Font("Verdana Pro Cond", 0, 12)); // NOI18N
        BotonRegistros.setText("Registros");
        BotonRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistrosActionPerformed(evt);
            }
        });

        eliminarTransmision.setFont(new java.awt.Font("Verdana Pro Cond", 0, 12)); // NOI18N
        eliminarTransmision.setText("Eliminar");
        eliminarTransmision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarTransmisionActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Verdana Pro Cond", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("*Campo número: \"ET\" seguido de 8 números");

        jLabel10.setFont(new java.awt.Font("Verdana Pro Cond", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("*Campo TIM: 11 números y una letra");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(27, 27, 27)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textNomTra, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textNumTra, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(textTipTra, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textTimTra, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(textEstTra, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(insertTransmisiones, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modificarTransmisiones))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotonRegistros)
                            .addComponent(eliminarTransmision, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textTimTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(textTipTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(textNumTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(insertTransmisiones)
                            .addComponent(BotonRegistros))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(eliminarTransmision)
                        .addComponent(modificarTransmisiones))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textEstTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(textNomTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addContainerGap())
        );

        botonConsultas.setFont(new java.awt.Font("Verdana Pro Cond", 0, 12)); // NOI18N
        botonConsultas.setText("Consultas");
        botonConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultasActionPerformed(evt);
            }
        });

        botonMenu.setFont(new java.awt.Font("Verdana Pro Cond", 0, 12)); // NOI18N
        botonMenu.setText("Menu");
        botonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenuActionPerformed(evt);
            }
        });

        botonArmamento.setFont(new java.awt.Font("Verdana Pro Cond", 0, 12)); // NOI18N
        botonArmamento.setText("Armamento");
        botonArmamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonArmamentoActionPerformed(evt);
            }
        });

        botonVehiculos.setFont(new java.awt.Font("Verdana Pro Cond", 0, 12)); // NOI18N
        botonVehiculos.setText("Vehículos");
        botonVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVehiculosActionPerformed(evt);
            }
        });

        botonPersonal.setFont(new java.awt.Font("Verdana Pro Cond", 0, 12)); // NOI18N
        botonPersonal.setText("Personal");
        botonPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPersonalActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Verdana Pro Cond", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TRANSMISIONES");

        //jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Insignia militar.png"))); // NOI18N

        //jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Insignia militar.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addGap(420)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(botonPersonal)
                                .addGap(87, 87, 87)
                                .addComponent(botonVehiculos)
                                .addGap(91, 91, 91)
                                .addComponent(botonArmamento)
                                .addGap(91, 91, 91)
                                .addComponent(botonConsultas)
                                .addGap(86, 86, 86)
                                .addComponent(botonMenu))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 48, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonConsultas)
                    .addComponent(botonMenu)
                    .addComponent(botonArmamento)
                    .addComponent(botonVehiculos)
                    .addComponent(botonPersonal))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertTransmisionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertTransmisionesActionPerformed
        
        /*Creamos nos variables para comprobar que esten en el campo numero de transmision
        y que ademas no exista un mismo registro con numero de arma*/
        char letraE = 'E';
        char letraT = 'T';
        boolean existe = false;
        
        /* verificamos que los campos no estan vacios y siguen el formato establecido
        Esto lo haremos mediante varios condicionales*/
        if(!"".equals(textNumTra.getText()) && !"".equals(textNomTra.getText())
                && !"".equals(textTipTra.getText()) && !"".equals(textEstTra.getText())
                && !"".equals(textTimTra.getText())){
                
            if(textTimTra.getText().length()!=12 || Character.isLetter(textTimTra.getText().charAt(11))==false){
            
                JOptionPane.showMessageDialog(null, "El formato del campo TIM no es correcto");
           
            }else if(textNumTra.getText().length()!=10 || textNumTra.getText().charAt(0)!=letraE
                || textNumTra.getText().charAt(1)!=letraT){
            
                JOptionPane.showMessageDialog(null, "El formato del campo numero"
                        + " de transmision no es correcto");
            
            }else{
                
                //Recorremos la tabla para verificar que no exista registo igual
                for(int i=0; i<tablaTransmisiones.getRowCount(); i++){
                    String NtransmisionTabla = tablaTransmisiones.getValueAt(i, 0).toString();
                    if(textNumTra.getText().equals(NtransmisionTabla)){
                        existe = true; 
                    }
                }
                //Mensaje de error si el campo ya existe
                if(existe==true){
                    JOptionPane.showMessageDialog(null, "Ya existe un registro "
                        + "con el mismo campo numero de transmision");
                }else{
                    //Introducimos lo registros 
                    transmisionesClass.setNumeroTransmision(textNumTra.getText());
                    transmisionesClass.setNombreTransmision(textNomTra.getText());
                    transmisionesClass.setTipo(textTipTra.getText());
                    transmisionesClass.setEstado(textEstTra.getText());
                    transmisionesClass.setTIM(textTimTra.getText());
             
                    transmisiones.insertarTransmision(transmisionesClass);
                    listaTransmisiones();
                    limpiarTranmisiones();
                    JOptionPane.showMessageDialog(null, "Registro introducido");
                }
            }
                
        }else if(!"".equals(textNumTra.getText()) && !"".equals(textNomTra.getText())
                && !"".equals(textTipTra.getText()) && !"".equals(textEstTra.getText())){
            
            
            if(textNumTra.getText().length()!=10 || textNumTra.getText().charAt(0)!=letraE
                || textNumTra.getText().charAt(1)!=letraT){
            
                JOptionPane.showMessageDialog(null, "El formato del campo numero"
                        + " de transmision no es correcto");
            
            }else{
                
                //Recorremos la tabla para verificar que no exista registo igual
                for(int i=0; i<tablaTransmisiones.getRowCount(); i++){
                    String NtransmisionTabla = tablaTransmisiones.getValueAt(i, 0).toString();
                    if(textNumTra.getText().equals(NtransmisionTabla)){
                        existe = true; 
                    }
                }
                //Mensaje de error si el campo ya existe
                if(existe==true){
                    JOptionPane.showMessageDialog(null, "Ya existe un registro "
                        + "con el mismo campo numero de transmision");
                }else{
                
                    //Introducimos los registros
                    transmisionesClass.setNumeroTransmision(textNumTra.getText());
                    transmisionesClass.setNombreTransmision(textNomTra.getText());
                    transmisionesClass.setTipo(textTipTra.getText());
                    transmisionesClass.setEstado(textEstTra.getText());
            
                    transmisiones.insertarTransmision(transmisionesClass);
                    listaTransmisiones();
                    limpiarTranmisiones();
                    JOptionPane.showMessageDialog(null, "Registro introducido");
                }
            }
            
        }else{
            
            JOptionPane.showMessageDialog(null, "Aún hay "
                    + "campos sin rellenar");
            
        }
        
    }//GEN-LAST:event_insertTransmisionesActionPerformed

    private void BotonRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistrosActionPerformed
        //Obtenemos los registros de nuestra base de datos
        listaTransmisiones();
        
    }//GEN-LAST:event_BotonRegistrosActionPerformed

    private void tablaTransmisionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaTransmisionesMouseClicked
        
        //Obtenemos los valores al hacer click en un registro
        int fila = tablaTransmisiones.rowAtPoint(evt.getPoint());
        textNumTra.setText(tablaTransmisiones.getValueAt(fila, 0).toString());
        textNomTra.setText(tablaTransmisiones.getValueAt(fila, 1).toString());
        textTipTra.setText(tablaTransmisiones.getValueAt(fila, 2).toString());
        textEstTra.setText(tablaTransmisiones.getValueAt(fila, 3).toString());
  
        Object tim = tablaTransmisiones.getValueAt(fila, 4);
        if (tim != null) {
            textTimTra.setText(tim.toString());
        } else {
            textTimTra.setText("");
        }
        
    }//GEN-LAST:event_tablaTransmisionesMouseClicked

    private void eliminarTransmisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarTransmisionActionPerformed
    
        //Eliminamos por el numero de transmision, por tanto verificamos que no este vacio
         if(!"".equals(textNumTra.getText())){
            
            int pregunta = JOptionPane.showConfirmDialog(null,
                    "Se eliminará el registro. ¿Estas seguro? ");
            //Hacemos la pregunta de seguridad para borrar el registro
            if(pregunta==0){
                
                //Pregunta de seguridad antes de borrar el registro
                String numTransmision = textNumTra.getText();
                transmisiones.eliminarTransmision(numTransmision);
                listaTransmisiones();
                limpiarTranmisiones();
                JOptionPane.showMessageDialog(null, "Registro eliminado");
            }
           
        }
        
    }//GEN-LAST:event_eliminarTransmisionActionPerformed

    private void modificarTransmisionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarTransmisionesActionPerformed
        
        //Declaramos los variables de tipo char, para verificar que esten en el campo numero transmisiones
        char letraE= 'E';
        char letraT='T';
        
        /*Verificamos tanto que este un registro seleccionado, como que los campos no sean nulos
        y que estos cumplan con el formato especificado*/
        if("".equals(textNumTra.getText())){
            
            JOptionPane.showMessageDialog(null, "No ha "
                    + "seleccionado ningun registro");
            
        }else if (!"".equals(textNomTra.getText()) && !"".equals(textTipTra.getText())
                && !"".equals(textEstTra.getText()) && !"".equals(textTimTra.getText())){
            
            if(textTimTra.getText().length()!=12 || Character.isLetter(textTimTra.getText().charAt(11))==false){
            
           JOptionPane.showMessageDialog(null, "El formato del campo TIM no es correcto");
           
            }else if(textNumTra.getText().length()!=10 || textNumTra.getText().charAt(0)!=letraE
                || textNumTra.getText().charAt(1)!=letraT){
            
            JOptionPane.showMessageDialog(null, "El formato del campo numero"
                    + " de transmision no es correcto");
            
            }else{
            
             //Introducimos lo datos en la tabla 
            transmisionesClass.setNumeroTransmision(textNumTra.getText());
            transmisionesClass.setNombreTransmision(textNomTra.getText());
            transmisionesClass.setTipo(textTipTra.getText());
            transmisionesClass.setEstado(textEstTra.getText());
            transmisionesClass.setTIM(textTimTra.getText());
           
            transmisiones.modificarTransmisiones(transmisionesClass);
                limpiarTranmisiones();
                listaTransmisiones(); 
                JOptionPane.showMessageDialog(null, "Registro modificado");
            }
            
        }else if(!"".equals(textNomTra.getText()) && !"".equals(textTipTra.getText())
                && !"".equals(textEstTra.getText())){
            
            if(textNumTra.getText().length()!=10 || textNumTra.getText().charAt(0)!=letraE
                || textNumTra.getText().charAt(1)!=letraT){
            
            JOptionPane.showMessageDialog(null, "El formato del campo numero"
                    + " de transmision no es correcto");
            
            }else{
            
            //Introducimos los datos en la tabla
            transmisionesClass.setNumeroTransmision(textNumTra.getText());
            transmisionesClass.setNombreTransmision(textNomTra.getText());
            transmisionesClass.setTipo(textTipTra.getText());
            transmisionesClass.setEstado(textEstTra.getText());
            
            transmisiones.modificarTransmisiones(transmisionesClass);
                limpiarTranmisiones();
                listaTransmisiones();
                JOptionPane.showMessageDialog(null, "Registro introducido");
            }    
            
        }else{
            
            JOptionPane.showMessageDialog(null, "Hay campos sin rellenar");
           
        }
        
    }//GEN-LAST:event_modificarTransmisionesActionPerformed

    private void botonPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPersonalActionPerformed
        // Vamos a personal
        personalUI = new PersonalUI();
        personalUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonPersonalActionPerformed

    private void botonArmamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonArmamentoActionPerformed
        // Vamos a la ventana armamento
        armamentoUI = new ArmamentoUI();
        armamentoUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonArmamentoActionPerformed

    private void botonVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVehiculosActionPerformed
        // Vamos a la ventana de vehiculos
        vehiculosUI= new VehiculosUI();
        vehiculosUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonVehiculosActionPerformed

    private void botonConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultasActionPerformed
        // Vamos al menu consultas
        consultasUI= new ConsultaUI();
        consultasUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonConsultasActionPerformed

    private void botonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenuActionPerformed
        //Vamos al principal
        menuUI = new MenuUI();
        menuUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonMenuActionPerformed

    public void limpiarTranmisiones(){
    //Con este metodo, limpiamos los campos de los Jtexfields   
        textNumTra.setText("");
        textNomTra.setText("");
        textTipTra.setText("");
        textEstTra.setText("");
        textTimTra.setText("");
         
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransmisionesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransmisionesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransmisionesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransmisionesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransmisionesUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonRegistros;
    private javax.swing.JButton botonArmamento;
    private javax.swing.JButton botonConsultas;
    private javax.swing.JButton botonMenu;
    private javax.swing.JButton botonPersonal;
    private javax.swing.JButton botonVehiculos;
    private javax.swing.JButton eliminarTransmision;
    private javax.swing.JButton insertTransmisiones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificarTransmisiones;
    private javax.swing.JTable tablaTransmisiones;
    private javax.swing.JTextField textEstTra;
    private javax.swing.JTextField textNomTra;
    private javax.swing.JTextField textNumTra;
    private javax.swing.JTextField textTimTra;
    private javax.swing.JTextField textTipTra;
    // End of variables declaration//GEN-END:variables
}
