/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import clases.Vehiculos;
import clases.VehiculosClass;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Manuel
 */
public class VehiculosUI extends javax.swing.JFrame {

    //Creamos los objetos que nos harán falta para añadirle funcionalidad a la interfaz
    VehiculosClass vehiculoClass = new VehiculosClass();
    Vehiculos vehiculo = new Vehiculos();
    DefaultTableModel tablaModelo;
    ArmamentoUI armamentoUI;
    TransmisionesUI transmisionesUI;
    PersonalUI personalUI;
    ConsultaUI consultasUI;
    MenuUI menuUI;
    
    public VehiculosUI() {
        initComponents();
        //setIconImage(new ImageIcon(getClass().getResource("/resources/insignia.png")).getImage());
        this.setLocationRelativeTo(null);
    }
    
    public void listaDeVehiculos(){
        
         //Creamos una lista, y la tabla para listar el personal 
        List <VehiculosClass> listaVehiculos = vehiculo.listaVehiculos();
        tablaModelo = (DefaultTableModel) tablaVehiculos.getModel();
        Object[] object = new Object[5];
        
        tablaModelo.setRowCount(0);
        
        for (int i = 0; i < listaVehiculos.size(); i++) {
            //Recorremos los registros, añadiendolos al Object
            object[0] = listaVehiculos.get(i).getMatriculaVehiculo();
            object[1] = listaVehiculos.get(i).getNombreVehiculo();
            object[2] = listaVehiculos.get(i).getTipo();
            object[3] = listaVehiculos.get(i).getKilometros();
            object[4] = listaVehiculos.get(i).getEstado();
            
            //Añadimos el objeto a la tabla 
            tablaModelo.addRow(object);
            
        }
        //Añadimos la tabla, a la tabla de nuestra interfaz 
        tablaVehiculos.setModel(tablaModelo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        botonPersonal = new javax.swing.JButton();
        botonArmamento = new javax.swing.JButton();
        botonTransmisiones = new javax.swing.JButton();
        botonMenu = new javax.swing.JButton();
        botonConsultas = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textMatVeh = new javax.swing.JTextField();
        textNomVeh = new javax.swing.JTextField();
        textKilVeh = new javax.swing.JTextField();
        textTipVeh = new javax.swing.JTextField();
        textEstVeh = new javax.swing.JTextField();
        InsertVehiculo = new javax.swing.JButton();
        modificarVehiculo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVehiculos = new javax.swing.JTable();
        BotonRegistros = new javax.swing.JButton();
        eliminarVehiculo = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));

        botonPersonal.setFont(new java.awt.Font("Verdana Pro Cond", 0, 12)); // NOI18N
        botonPersonal.setText("Personal");
        botonPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPersonalActionPerformed(evt);
            }
        });

        botonArmamento.setFont(new java.awt.Font("Verdana Pro Cond", 0, 12)); // NOI18N
        botonArmamento.setText("Armamento");
        botonArmamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonArmamentoActionPerformed(evt);
            }
        });

        botonTransmisiones.setFont(new java.awt.Font("Verdana Pro Cond", 0, 12)); // NOI18N
        botonTransmisiones.setText("Transmisiones");
        botonTransmisiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTransmisionesActionPerformed(evt);
            }
        });

        botonMenu.setFont(new java.awt.Font("Verdana Pro Cond", 0, 12)); // NOI18N
        botonMenu.setText("Menu");
        botonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenuActionPerformed(evt);
            }
        });

        botonConsultas.setFont(new java.awt.Font("Verdana Pro Cond", 0, 12)); // NOI18N
        botonConsultas.setText("Consultas");
        botonConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultasActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Verdana Pro Cond", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("VEHICULOS");

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Verdana Pro Cond", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Matrícula");

        jLabel2.setFont(new java.awt.Font("Verdana Pro Cond", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Verdana Pro Cond", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kilómetros");

        jLabel4.setFont(new java.awt.Font("Verdana Pro Cond", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tipo");

        jLabel5.setFont(new java.awt.Font("Verdana Pro Cond", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Estado");

        InsertVehiculo.setFont(new java.awt.Font("Verdana Pro Cond", 0, 12)); // NOI18N
        InsertVehiculo.setText("Insertar");
        InsertVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertVehiculoActionPerformed(evt);
            }
        });

        modificarVehiculo.setFont(new java.awt.Font("Verdana Pro Cond", 0, 12)); // NOI18N
        modificarVehiculo.setText("Modificar");
        modificarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarVehiculoActionPerformed(evt);
            }
        });

        tablaVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matrícula", "Nombre", "Tipo", "Kilometros", "Estado"
            }
        ));
        tablaVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaVehiculosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaVehiculos);

        BotonRegistros.setFont(new java.awt.Font("Verdana Pro Cond", 0, 12)); // NOI18N
        BotonRegistros.setText("Registros");
        BotonRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistrosActionPerformed(evt);
            }
        });

        eliminarVehiculo.setFont(new java.awt.Font("Verdana Pro Cond", 0, 12)); // NOI18N
        eliminarVehiculo.setText("Eliminar");
        eliminarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarVehiculoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Verdana Pro Cond", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("*Campo matrícula: \"ET\" seguido de 8 números");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(textMatVeh, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(textTipVeh, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(textKilVeh, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textEstVeh, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(InsertVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(textNomVeh, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modificarVehiculo)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eliminarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonRegistros))
                .addGap(59, 59, 59))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(textMatVeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(textTipVeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(textEstVeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InsertVehiculo)
                            .addComponent(eliminarVehiculo))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textNomVeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(modificarVehiculo)
                        .addComponent(BotonRegistros))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(textKilVeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        //jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Insignia militar.png"))); // NOI18N

        //jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Insignia militar.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(450)
                                .addComponent(jLabel6))
                            .addComponent(botonTransmisiones))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(100)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 61, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(botonPersonal)
                        .addGap(115)
                        .addComponent(botonArmamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonConsultas)
                        .addGap(100)
                        .addComponent(botonMenu)
                        .addGap(130)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonPersonal)
                    .addComponent(botonArmamento)
                    .addComponent(botonTransmisiones)
                    .addComponent(botonConsultas)
                    .addComponent(botonMenu))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertVehiculoActionPerformed
        
        boolean existe = false;
        char letraE = 'E';
        char letraF = 'T';
        /*Verificamos que los campos no esten vacios, e insertamos el registro
        Tambien comprobamos el formato de los campos*/
        if(!"".equals(textMatVeh.getText()) || !"".equals(textNomVeh.getText())
                || !"".equals(textTipVeh.getText()) || !"".equals(textKilVeh.getText())
                || !"".equals(textEstVeh.getText())){
            
            if(textMatVeh.getText().length()!=10 || textMatVeh.getText().charAt(0)!=letraE
                || textMatVeh.getText().charAt(1)!=letraF){
            
            JOptionPane.showMessageDialog(null, "El formato del campo matricula  no es correcto");
            
            }else{
                
                //Recorremos la tabla para verificar que no exista registo igual
                for(int i=0; i<tablaVehiculos.getRowCount(); i++){
                    String MVehiculoTabla = tablaVehiculos.getValueAt(i, 0).toString();
                    if(textMatVeh.getText().equals(MVehiculoTabla)){
                        existe = true; 
                    }
                }
                //Mensaje de error si el campo ya existe
                if(existe==true){
                    JOptionPane.showMessageDialog(null, "Ya existe un registro "
                        + "con el mismo campo numero de matricula");
                }else{
            
                    //añadimos el registro 
                    vehiculoClass.setMatriculaVehiculo(textMatVeh.getText());
                    vehiculoClass.setNombreVehiculo(textNomVeh.getText());
                    vehiculoClass.setTipo(textTipVeh.getText());
                    vehiculoClass.setKilometros(textKilVeh.getText());
                    vehiculoClass.setEstado(textEstVeh.getText());
            
                    vehiculo.insertarVehiculo(vehiculoClass);
                    listaDeVehiculos();
                    limpiarVehiculo();
                    JOptionPane.showMessageDialog(null, "Registro introducido"); 
                }
            }
            
        }else{
            
            JOptionPane.showMessageDialog(null, "Hay campos sin rellenar");
        }
        

    }//GEN-LAST:event_InsertVehiculoActionPerformed

    private void BotonRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistrosActionPerformed
        // Listamos los vehiculos
        listaDeVehiculos();
        
    }//GEN-LAST:event_BotonRegistrosActionPerformed

    private void tablaVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaVehiculosMouseClicked
        
        //Pinchando en la fila, añadimos los valores de la tabla los Jtextfield
        int fila = tablaVehiculos.rowAtPoint(evt.getPoint());
        textMatVeh.setText(tablaVehiculos.getValueAt(fila, 0).toString());
        textNomVeh.setText(tablaVehiculos.getValueAt(fila, 1).toString());
        textTipVeh.setText(tablaVehiculos.getValueAt(fila, 2).toString());
        textKilVeh.setText(tablaVehiculos.getValueAt(fila, 3).toString());
        textEstVeh.setText(tablaVehiculos.getValueAt(fila, 4).toString());
        
    }//GEN-LAST:event_tablaVehiculosMouseClicked

    private void eliminarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarVehiculoActionPerformed
        
        //Verificamos que el campo matricula no este vacio, para eliminar el registro
        if(!"".equals(textMatVeh.getText())){
             //Realizamos pregunta de seguridad antes de borrar el registro
            int pregunta = JOptionPane.showConfirmDialog(null,
                    "Se eliminará el registro. ¿Estas seguro? ");
            
            if(pregunta==0){
                //Eliminamos el registro
                String matriculaVehiculo = textMatVeh.getText();
                vehiculo.eliminarVehiculo(matriculaVehiculo);
                listaDeVehiculos();
                limpiarVehiculo();
                
            }
            
            
        }
        
    }//GEN-LAST:event_eliminarVehiculoActionPerformed

    private void modificarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarVehiculoActionPerformed
        
        char letraE = 'E';
        char letraT = 'T';
        
        /*Verificamos que el campo matricula no este vacio y que el formato de los 
        datos sea correcto*/
        if("".equals(textMatVeh.getText())){
            
            JOptionPane.showMessageDialog(null, "No ha "
                    + "seleccionado ningun registro");
            
        }else if (!"".equals(textNomVeh.getText()) && !"".equals(textTipVeh.getText())
                && !"".equals(textKilVeh.getText()) && !"".equals(textEstVeh.getText())){
            
            if(textMatVeh.getText().length()!=10 || textMatVeh.getText().charAt(0)!=letraE
            || textMatVeh.getText().charAt(1)!=letraT){
            
                JOptionPane.showMessageDialog(null, "El formato del campo matricula  no es correcto");
            
            }else{
                vehiculoClass.setMatriculaVehiculo(textMatVeh.getText());
                vehiculoClass.setNombreVehiculo(textNomVeh.getText());
                vehiculoClass.setTipo(textTipVeh.getText());
                vehiculoClass.setKilometros(textKilVeh.getText());
                vehiculoClass.setEstado(textEstVeh.getText());
           
                vehiculo.modificarVehiculo(vehiculoClass);
                 JOptionPane.showMessageDialog(null, "Registro modificado"); 
                limpiarVehiculo();
                listaDeVehiculos(); 
            }
            
        }else{
            
            JOptionPane.showMessageDialog(null, "Hay campos sin rellenar");
         
        }
        
    }//GEN-LAST:event_modificarVehiculoActionPerformed

    private void botonPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPersonalActionPerformed
        // Boton que nos llevar a personal
        personalUI = new PersonalUI();
        personalUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonPersonalActionPerformed

    private void botonArmamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonArmamentoActionPerformed
        // boton que nos lleva a armamento
        armamentoUI = new ArmamentoUI();
        armamentoUI.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_botonArmamentoActionPerformed

    private void botonTransmisionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTransmisionesActionPerformed
        // Boton que nos lleva a transmisiones
        transmisionesUI = new TransmisionesUI();
        transmisionesUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonTransmisionesActionPerformed

    private void botonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenuActionPerformed
        // Boton que nos lleva a menu principal
        menuUI = new MenuUI();
        menuUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonMenuActionPerformed

    private void botonConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultasActionPerformed
        // Boton que nos lleva a consultas
        consultasUI= new ConsultaUI();
        consultasUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonConsultasActionPerformed

    public void limpiarVehiculo(){
        //Vaciamos los jtextFielfd
        textMatVeh.setText("");
        textNomVeh.setText("");
        textTipVeh.setText("");
        textKilVeh.setText("");
        textEstVeh.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehiculosUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehiculosUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehiculosUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehiculosUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VehiculosUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonRegistros;
    private javax.swing.JButton InsertVehiculo;
    private javax.swing.JButton botonArmamento;
    private javax.swing.JButton botonConsultas;
    private javax.swing.JButton botonMenu;
    private javax.swing.JButton botonPersonal;
    private javax.swing.JButton botonTransmisiones;
    private javax.swing.JButton eliminarVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificarVehiculo;
    private javax.swing.JTable tablaVehiculos;
    private javax.swing.JTextField textEstVeh;
    private javax.swing.JTextField textKilVeh;
    private javax.swing.JTextField textMatVeh;
    private javax.swing.JTextField textNomVeh;
    private javax.swing.JTextField textTipVeh;
    // End of variables declaration//GEN-END:variables
}
